# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/osx-64/bzip2-1.0.6-h1de35cc_1002.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ca-certificates-2019.3.9-hecc5488_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libgfortran-3.0.1-0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libsodium-1.0.16-h1de35cc_1001.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/xz-5.2.4-h1de35cc_1001.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zlib-1.2.11-h1de35cc_1004.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libpng-1.6.37-h2573ce8_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/openblas-0.3.6-hd44dcd8_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/openssl-1.1.1b-h01d97ff_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tk-8.6.9-ha441bb4_1001.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/freetype-2.10.0-h24853df_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/anaconda-custom-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/appnope-0.1.0-py37_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backcall-0.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/certifi-2019.3.9-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/click-7.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/decorator-4.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ipython_genutils-0.2.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcxx-8.0.0-2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcxxabi-8.0.0-2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libffi-3.2.1-h6de7cb9_1006.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ncurses-6.1-h0a44026_1002.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zeromq-4.3.1-h0a44026_1000.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/readline-7.0-hcfe32e1_1001.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/sqlite-3.26.0-h1765d9f_1001.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python-3.7.3-h0d93f26_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/kiwisolver-1.1.0-py37h770b8ee_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/parso-0.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pickleshare-0.7.5-py37_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ptyprocess-0.6.0-py_1001.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyparsing-2.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-dotenv-0.10.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pytz-2019.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pyzmq-18.0.1-py37h2d07e9b_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/setuptools-41.0.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/six-1.12.0-py37_1000.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tornado-6.0.2-py37h01d97ff_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wcwidth-0.1.7-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cycler-0.10.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/jedi-0.13.3-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pexpect-4.7.0-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pygments-2.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-dateutil-2.8.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/traitlets-4.3.2-py37_1000.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/wheel-0.33.4-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyter_core-4.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pip-19.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/prompt_toolkit-2.0.9-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ipython-7.5.0-py37h24bf2e0_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyter_client-5.2.4-py_3.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ipykernel-5.1.0-py37h24bf2e0_1002.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/matplotlib-3.0.3-py37_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/matplotlib-base-3.0.3-py37habd5b94_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pandas-0.24.2-py37h0a44026_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libblas-3.8.0-9_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcblas-3.8.0-9_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/liblapack-3.8.0-9_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/numpy-1.16.3-py37hdf140aa_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/scipy-1.2.1-py37hbd7caa9_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/scikit-learn-0.20.3-py37hca23c92_1.tar.bz2
